using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication3.Controllers
{
    public class DoctorWhoData
    {
        public static string item1()
        {
                return "Skaro Cult of Skaro DON'T BLINK! Delete. Delete. Delete. Cult of Skaro River Song K-9 You will be exterminated! Bad Wolf  Mickey Smith Allons-y, Alonso! Mickey Smith Reverse the polarity of the neutron flow The angels have the phone box Davros K-9 You are better at dying Time Lord Reverse the polarity of the positron flow Stormageddon, Dark Lord of All You will be exterminated! Reverse the polarity of the positron flow River Song Hello Sweetie. EXTERMINATE! K-9 Galifrey Amy Pond EXTERMINATE! Reverse the polarity of the neutron flow Geronimo! Bad Wolf  Donna Noble Bow ties are cool. Hello sweetie Geronimo! Bow ties are cool Reverse the polarity of the neutron flow I really hate stairs. EXTERMINATE ALL STAIRCASES! Bow ties are cool RUN! Hello sweetie! Bow ties are cool DON'T BLINK! the oncoming storm You are better at dying IT is the Doctor! Enemy of the Daleks! Galifreyan You are better at dying Spoilers! Reverse the polarity of the neutron flow wibbly-wobbly timey-wimey Captain Jack Harkness Rude and not ginger the girl who waited you are not alone in the universe Cult of Skaro Raxacoricofallapatorius Amy Pond Bananas are good You will be exterminated! the girl who waited Demon's Run It's bigger on the inside! EXTERMINATE! the oncoming storm The Silence is Coming! It's bigger on the inside! Amy Pond Spoilers! Dalekanium You are better at dying Spoilers! EXTERMINATE! I wear a fez now, fezzes are cool It's bigger on the inside! River Song the girl who waited I wear a fez now, fezzes are cool wibbly wobbly timey wimey Dalekanium Spoilers! EXTERMINATE! I hereby invoke The Shadow Proclamation! Cult of Skaro Hello Sweetie. Puny Human! Skaro Captain Jack Harkness The Supreme Dalek Skaro Emperor of the Daleks The Silence is Coming! I am a Dalek Fantastic! Cult of Skaro Spoilers! You will be exterminated! Amy Pond Bring the Humans to me Rude and not ginger";
        }

        public static string item2()
        {
            return "Captain Jack Harkness Dalekanium Silence will fall The Silence is Coming! Hello sweetie! K-9 Demon's Run The Master River Song IT is the Doctor! Enemy of the Daleks! Donna Noble has left the library. Donna Noble has been saved. Mickey Smith Donna Noble Bad Wolf  Hey, who turned out the lights? Rose Tyler Tick tock goes the clock... the girl who waited K-9 Cybermen Cult of Skaro Bow ties are cool The socks with holes, dummy! Reverse the polarity of the positron flow Delete. Delete. Delete. Delete. Delete. Delete. The Master Hello sweetie! Rude and not ginger Demon's Run Hello Sweetie. Hello Sweetie. Raxacoricofallapatorius Time War Rude and not ginger EXTERMINATE! Skaro EXTERMINATE! Rory the Roman wibbly wobbly timey wimey puny human Would you like a jelly baby? Allons-y, Alonso! I hereby invoke The Shadow Proclamation! Bad Wolf the oncoming storm MY VISION IS IMPAIRED! K-9 I really hate stairs. EXTERMINATE ALL STAIRCASES! Puny Human! Geronimo! Would you like a jelly baby? Donna Noble Bad Wolf  Donna Noble YOU WILL OBEY! Bad Wolf  Captain Jack Harkness Hello Sweetie. Captain Jack Harkness Cybermen Silence will fall Hello, Captain Jack Harkness.  It's bigger on the inside! The Shadow Proclamation Bad Wolf K-9 Bananas are good RUN! Allons-y I wear a fez now, fezzes are cool Demon's Run wibbly-wobbly timey-wimey Would you like a jelly baby? Galifrey Bananas are good Skaro Time Lord Cybermen I wear a fez now, fezzes are cool Cult of Skaro Allons-y Rory the Roman The Doctor River Song Mickey Smith The socks with holes, dummy! I really hate stairs. EXTERMINATE ALL STAIRCASES! EXTERMINATE! Time War EXTERMINATE! Fantastic! Skaro YOU WILL OBEY! Geronimo! Time Lord EXTERMINATE! Galifreyan Amy Pond EXTERMINATE! The Supreme Dalek I really hate stairs. EXTERMINATE ALL STAIRCASES! YOU WILL OBEY! Donna Noble has left the library. Donna Noble has been saved. Reverse the polarity of the neutron flow Rose Tyler Time War Raxacoricofallapatorius Reverse the polarity of the positron flow I really hate stairs. EXTERMINATE ALL STAIRCASES! EXTERMINATE! I wear a fez now, fezzes are cool you are not alone in the universe Time Lord Skaro Rory the Roman Puny Human! I hereby invoke The Shadow Proclamation! Cybermen ninehundred  Cult of Skaro Emperor of the Daleks I wear a fez now, fezzes are cool EXTERMINATE! DON'T BLINK! EXTERMINATE! Rose Tyler Cybermen Dalekanium Rose Tyler The angels have the phone box Davros wibbly-wobbly timey-wimey Bow ties are cool. Hello sweetie! Would you like a jelly baby? K-9 DON'T BLINK! Amy Pond Puny Human! Rude and not ginger Demon's Run Rory the Roman The angels have the phone box I wear a fez now, fezzes are cool wibbly-wobbly timey-wimey The angels have the phone box Time Lord Hey, who turned out the lights? You are better at dying The Silence is Coming!";
        }
    }
}